### ISSUE TITLE
locale.language and locale.toLanguageTag() don't work for javascript

### ISSUE THREAD

**Issue by yebaital** [adrielcafe/lyricist#16]
locale.langue produces a null pointer exception in JS, and locale.toLanguageTag() show the error
`An operation is not implemented: implement native toLanguageTag`

**Comment by adrielcafe** [comment]
This was an bug on Compose Multiplatform but seems to be fixed in the latest builds ([#3250](https://github.com/JetBrains/compose-multiplatform/issues/3250), [#2815](https://github.com/JetBrains/compose-multiplatform/issues/2815)). 

You can update Lyricist to [1.5.0](https://github.com/adrielcafe/lyricist/releases/tag/1.5.0) and check if works. If not, feel free to reopen the issue and I'll try to do some workaround.
